### PR TITLE
feat: improve custom error output

### LINKED ISSUE #30: FEATURE | Improve custom error output
# FEATURE

## CONTEXT

Custom error output is currently displayed on a single line, and it is separated by the pipe symbol “|”.

## GOAL

Create an output where each error is separated by new lines, adding four whitespace at the beginning. Each line will have a subtitle indicating what type of output is being discussed, whether it is the description or the raw error output.

## CURRENTLY

These are the real examples, every line is one type of error. These follow the next structure: “_Error: General error | Specific error | Technical error_”.
```text
Error: Version manager error | Failed to download version from 'www.fake.com' | builder error
Error: Version manager error | Failed to download Python from 'https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz.fake' | Status: 404 Not Found
Error: Version manager error | Failed to create download file '/home/wolf/.shuru/python/3.10.2/python.tgz' | Permission denied (os error 13)
Error: Version manager error | Failed to run command 'cd "/home/wolf/.shuru/python/3.10.2/Python-3.10.2" && "./configurex" "--prefix=/home/wolf/.shuru/python/3.10.2/install"' | No such file or directory (os error 2)
Error: Version manager error | Python build command failed | Exit code: 1
Error: Version manager error | Python build command failed | Exit code: 1 > configure: error: unrecognized option: `-abcdef'
Error: Version manager error | Failed to remove downloaded archive '/home/wolf/.shuru/python/3.10.2/python.tgz/xxx' | Not a directory (os error 20)
```

There are other types of errors which return two errors. In the below example, the format is “_Error: General error | Specific error | General error | Specific error | Technical error_”
```text
Error: Version manager error | Failed to extract archive '/home/wolf/.shuru/python/3.10.2/python.tgz' to '/home/wolf/.shuru/python/3.10.2' | Command execution error | Failed to open tar.gz file | Permission denied (os error 13)
```

### When it throws one error.

```text
Error: Version manager error
    Description: Failed to remove downloaded archive '/home/wolf/.shuru/python/3.10.2/python.tgz/xxx'
    Technical: Not a directory (os error 20)
```

```text
Error: Version manager error
    Description: Failed to download Python from 'https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz.fake'
    Technical: Status: 404 Not Found
```

### Special cases when the error throws two technical outputs.

```text
Error: Version manager error
    Description: Python build command failed
    Technical: Exit code: 1
    Technical: configure: error: unrecognized option: `-abcdef'
```
### Cases where it throws two errors.

```text
Error: Version manager error
    Description: Failed to extract archive '/home/wolf/.shuru/python/3.10.2/python.tgz' to '/home/wolf/.shuru/python/3.10.2'
Error: Command execution error
    Description: Failed to open tar.gz file
    Technical: Permission denied (os error 13)
```

## DEVELOPERS

The file for the errors is in `src/error.rs`. The errors are in `pub enum VersionManagerError`.

The implementation of these errors are in two files:
* `src/version_manager/python_version_manager.rs`.
* `src/version_manager/node_version_manager.rs`.

### TIP:

The resolution of this problem could be a little easy. In theory, only needs to add four spaces in the error file. 

## NOTE

This feature was discussed in this post: https://github.com/shuru-project/shuru/discussions/29.

### PR DESCRIPTION
**Pull request by andcscott**
This PR improves upon custom error messages as discussed in #29 and closes #30.

There were two errors I had difficulty testing: `UnableHomeDirectory` and `HomeDirectoryNotFound`. In both cases I reformatted the strings, but other errors were either triggered first (i.e. permissions) or I was unable to trick Rust into believing that the users home did not exist (i.e. `HOME="IdontExist" cargo run` just created "IdontExist" in the project root). Further testing can be done if needed, however I may need guidance.

Output:
```
Error: Configuration loading error
    Description: Invalid config file format
    Technical: Unknown version command for key `versions` at line 2 column 1
```

### CODE REVIEW

**Comment by airvzxf** [comment]
Thanks for your input, Scott. I hadn't checked the `UnableHomeDirectory` or `HomeDirectoryNotFound` errors, they were impossible.

Not more work for test, as you have, it is good.

Let me check do it a code review for your code.

**Comment by airvzxf** [comment]
This PR exceeded expectations, given its scope. Thank you very much for your contribution.

**Comment by airvzxf** [comment]
@andcscott, please check if your PR is showing in Hacktoberfest. Please check in 30 minutes, if not, let's wait 6 hours. If after this time, the PR is not in Hacktoberfest, I'll add a label in your PR.

**Comment by andcscott** [comment]
Yes I can see it :+1:  Thank you for checking! I can also see #41 just so you're aware, although it obviously doesn't show as "accepted" yet.

**Pull request merged**
